name: 'action-git-worktree-clean'
description: 'Checks the status of your git worktree'
author: 'Lee Briggs'
outputs:
  clean:
    description: 'If the worktree is clean or not'
runs:
  using: 'node12'
  main: 'dist/index.js'
